#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : websocket_client
Version  : 0.56.0
Release  : 58
URL      : https://files.pythonhosted.org/packages/c5/01/8c9c7de6c46f88e70b5a3276c791a2be82ae83d8e0d0cc030525ee2866fd/websocket_client-0.56.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c5/01/8c9c7de6c46f88e70b5a3276c791a2be82ae83d8e0d0cc030525ee2866fd/websocket_client-0.56.0.tar.gz
Summary  : WebSocket client for Python. hybi13 is supported.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: websocket_client-bin = %{version}-%{release}
Requires: websocket_client-license = %{version}-%{release}
Requires: websocket_client-python = %{version}-%{release}
Requires: websocket_client-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
websocket-client
        =================
        
        websocket-client module  is WebSocket client for python. This provide the low level APIs for WebSocket. All APIs are the synchronous functions.
        
        websocket-client supports only hybi-13.
        
        
        License
        =======
        
         - BSD
        
        Installation
        ============
        
        This module is tested on Python 2.7 and Python 3.4+.
        
        Type "python setup.py install" or "pip install websocket-client" to install.

%package bin
Summary: bin components for the websocket_client package.
Group: Binaries
Requires: websocket_client-license = %{version}-%{release}

%description bin
bin components for the websocket_client package.


%package license
Summary: license components for the websocket_client package.
Group: Default

%description license
license components for the websocket_client package.


%package python
Summary: python components for the websocket_client package.
Group: Default
Requires: websocket_client-python3 = %{version}-%{release}

%description python
python components for the websocket_client package.


%package python3
Summary: python3 components for the websocket_client package.
Group: Default
Requires: python3-core

%description python3
python3 components for the websocket_client package.


%prep
%setup -q -n websocket_client-0.56.0
cd %{_builddir}/websocket_client-0.56.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576017716
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/websocket_client
cp %{_builddir}/websocket_client-0.56.0/LICENSE %{buildroot}/usr/share/package-licenses/websocket_client/6ab0289d84ac622dd4a6efcf6b20d54e3e32f412
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wsdump.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/websocket_client/6ab0289d84ac622dd4a6efcf6b20d54e3e32f412

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
